server {
    listen 80;

    # Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Backend API (VM)
    location /api {
        proxy_pass http://192.168.31.33:5000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
